'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SAG_SBLM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aceptar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aceptar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Actualizar_Registro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actualizar_Registro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Agregar_Bien() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Agregar_Bien", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anular() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anular", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anular1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anular1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Autorizar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Autorizar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bene() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bene", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cancelar_Comprobante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancelar_Comprobante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cancelar_Formato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancelar_Formato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cargo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cargo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cerrar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cerrar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property cn() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cn", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Contabilidad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contabilidad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property databaseIII() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("databaseIII", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Editar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Editar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eliminar_Bienes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eliminar_Bienes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Excel_Logo_Home_Page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel_Logo_Home_Page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fachadacolor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fachadacolor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fondo_bene() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo_bene", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property garantia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("garantia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Actividades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Actividades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Actualizar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Actualizar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Ampliacion_Certificaciones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Ampliacion_Certificaciones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Ampliaciones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Ampliaciones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Ampliar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Ampliar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Anular() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Anular", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Aprobacion_Requerimiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Aprobacion_Requerimiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Autorizar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Autorizar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Base_Datos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Base_Datos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Bienes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Bienes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Buscar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Buscar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Caja_Chica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Caja_Chica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Calendario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Calendario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Catalogo_Bienes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Catalogo_Bienes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Catalogo_Obras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Catalogo_Obras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Catalogo_Servicios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Catalogo_Servicios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Certificcion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Certificcion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Clasificadpres() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Clasificadpres", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Configuracion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Configuracion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Configuracion_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Configuracion_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Contratos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Contratos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Correo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Correo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Cumplimiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Cumplimiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Desaprobar_Requerimiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Desaprobar_Requerimiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Devengar_OC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Devengar_OC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Devengar_OS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Devengar_OS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Editar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Editar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Eliminar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Eliminar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Encargos_Internos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Encargos_Internos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Estadistica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Estadistica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Estudio_Mercado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Estudio_Mercado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Extornar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Extornar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Firmar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Firmar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Fuentes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Fuentes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Garantias() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Garantias", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Generar_Solicitud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Generar_Solicitud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Giro_Caj_Chica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Giro_Caj_Chica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Giro_Encargos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Giro_Encargos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Giro_OC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Giro_OC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Giro_OS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Giro_OS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Giro_Planillas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Giro_Planillas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Giro_Varios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Giro_Varios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Giro_Viaticos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Giro_Viaticos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Grafico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Grafico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Guadar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Guadar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Imprimir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Imprimir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Metas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Metas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_NEA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_NEA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Nota_Modificatoria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Nota_Modificatoria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Nuevo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Nuevo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Nuevo_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Nuevo_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Nuevo_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Nuevo_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Nuevo_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Nuevo_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Orden_Compra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Orden_Compra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Orden_Servicio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Orden_Servicio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Otros_Registros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Otros_Registros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Otros_Reportes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Otros_Reportes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_PAC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_PAC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_PC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_PC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_PECOSA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_PECOSA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Penalidad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Penalidad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_PIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_PIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Planilla_276() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Planilla_276", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Planilla_CAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Planilla_CAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Planillas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Planillas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Planillas_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Planillas_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Procesos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Procesos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Proveedores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Proveedores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Quitar_Aprobacion_Requerimiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Quitar_Aprobacion_Requerimiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Rebajar_Orden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Rebajar_Orden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Rebajas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Rebajas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Rebajas_Certificacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Rebajas_Certificacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reducir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reducir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reenumerar_Orden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reenumerar_Orden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Registro_Contratos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Registro_Contratos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Registro_Convocatotrias() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Registro_Convocatotrias", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Registro_Legajo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Registro_Legajo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Registro_Prevision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Registro_Prevision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Registro_Trabajadores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Registro_Trabajadores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reportar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reportar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Devengados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Devengados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_General() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_General", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_General_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_General_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Giros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Giros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Legajo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Legajo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_NEA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_NEA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_PECOSA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_PECOSA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_PIM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_PIM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Planillas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Planillas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Requerimiento_Biene() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Requerimiento_Biene", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Requerimiento_Servicios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Requerimiento_Servicios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_SEACE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_SEACE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Servicios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Servicios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Trabajadores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Trabajadores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reporte_Transparencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reporte_Transparencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Reportes_Compras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Reportes_Compras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Salir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Salir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Servicios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Servicios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Siguiente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Siguiente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Siguiente_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Siguiente_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Solicitud_Certificacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Solicitud_Certificacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Solicitud_Certificacion_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Solicitud_Certificacion_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Usuarios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Usuarios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Viaticos_Asignaciones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Viaticos_Asignaciones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icono_Visualizar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icono_Visualizar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Image_Impuesto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image_Impuesto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Limpiar_Bienes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Limpiar_Bienes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Login_SAB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login_SAB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Logo_SBLM_copia() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo_SBLM_copia", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_Fondo_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_Fondo_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SAB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SAB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property SAG_SBLM() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SAG_SBLM", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saldo_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saldo_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
